### ISSUE TITLE
Add software composition analysis test for latest opendesk nextcloud container 

### ISSUE THREAD

**Issue by karsten-klein** [org-metaeffekt/metaeffekt-core#95]
Add SCA test for container

{
    "registry": "registry.opencode.de",
    "repository": "bmi/opendesk/components/platform-development/images/opendesk-nextcloud-php",
    "tag": "1.8.4@sha256:d51ca3e22a493d6dd625cf9bfa40f96481ba36894a9d3eed1e082eadaef72c5c",
}

Check whether nextcloud can be further decomposed.

**Comment by aleyeeey** [comment]
@karsten-klein do you mean something like [this](https://github.com/org-metaeffekt/metaeffekt-core/assets/60931442/6dfc0cdd-7078-43ff-8df2-54340c3252f7) for "3rdparty"? I created a new type and looked for 3rdparty tools, which is roughly only the php-composer stuff, so is this enough or would you need stuff further decomposed in here?

**Comment by aleyeeey** [comment]
@karsten-klein and would you like to split up the apps? lets say 
![this](https://github.com/org-metaeffekt/metaeffekt-core/assets/60931442/e30bb9ba-68ca-44df-8be2-cc7bba2a826a) with it's own node_modules, so it will be detected as an own "type", e.g. "NextcloudPDFViewer" or something? but how accurate can this get and would it even make sense and not be an overload? just some thoughts and questions

**Comment by aleyeeey** [comment]
[scan-inventory.xls](https://github.com/org-metaeffekt/metaeffekt-core/files/14883113/scan-inventory.xls)

**Comment by aleyeeey** [comment]
@karsten-klein 
What do you think about something like this? 
![image](https://github.com/org-metaeffekt/metaeffekt-core/assets/60931442/fa89ddb8-cd3b-4017-9cae-457c8b53361a)
We could collect all files belonging to that app within nextcloud, like all nodejs packages, etc.? would this make sense? then we would have several types
